"""empty message

Revision ID: 7800956e6aa7
Revises: 
Create Date: 2020-09-16 17:49:18.947570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7800956e6aa7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=12), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_date'), 'ticket', ['date'], unique=False)
    op.create_index(op.f('ix_ticket_number'), 'ticket', ['number'], unique=True)
    op.create_index(op.f('ix_ticket_time'), 'ticket', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_time'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_number'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_date'), table_name='ticket')
    op.drop_table('ticket')
    # ### end Alembic commands ###
